const monsterList ={
    monsters: [
    {
        name: "Ethan Cantrell",
        pics: ["ethan-cantrell-1", "ethan-cantrell-2","ethan-cantrell-3", "ethan-cantrell-4", "ethan-cantrell-5"],
        ogPic: "ethan-cantrell-og",
        urlName: "ethan-cantrell",
        bioText: [
            `delivers an acoustic blend of folk and punk, infused with ska and reggae sensibilities. His music is shaped by influences such as Green Day, Woody Guthrie, Streetlight Manifesto, and Pat the Bunny, creating a sound that's both unique and dynamic.`,
            `With 15 years of experience in playing music and running sound, Ethan has honed his craft both on stage and behind the scenes. His dedication to the art extends to the studio, where he has been producing music for the past 7 years, refining the sounds that define his style.`,
            `For the past 3 years, Ethan has been hosting open mics and showcases called "Musical Monsters," fostering a community of musicians and bringing new talent to the forefront. His experience in these settings has allowed him to develop a deep connection with audiences, making each performance memorable.`,
            `Known for his refined yet high-energy performances, Ethan knows how to engage an audience and keep them listening. Whether it’s an intimate venue or a lively bar, he’s ready to bring his passion for music to the stage, ensuring an experience that resonates with listeners.`
        ],
        spotifyUrl: "3TrHIZ92sj1YvABKrcJTQE?utm_source=generator&theme=0",
        fbLink: "https://www.facebook.com/ECMusician",
        igLink: "https://www.instagram.com/ethancantrellmusician/",
        ttLink: "https://www.tiktok.com/@ethancantrellmusician",
        ytLink: "https://www.youtube.com/channel/UC9fOxoEeGQmTzzXFTQEjqRA",
        bcLink: "",
    },
    {
        name: "Eric Ryan-Johnson",
        pics: ["erj-1", "erj-2", "erj-3", "erj-4", "erj-5"],
        ogPic: "erj-og",

        urlName: "eric-ryan-johnson",
        bioText: [
            `is a versatile musician based in Tulsa, Oklahoma, renowned for his skills as a vocalist, guitarist, and violinist. Originally from Madison, Wisconsin, he has cultivated a diverse musical career that spans several genres, including alt-acoustic rock and traditional Irish music.`,
            `Eric is deeply involved in both solo projects and collaborative efforts. His solo work features a discography with multiple albums, such as "Just a Lil' Bit of Love" (2021) and "Two Hours out of Nashville" (2022), which highlight his ability to seamlessly transition from heartfelt acoustic ballads to more experimental sounds.`,
            `In addition to his solo career, Eric is an accomplished fiddle player and instructor. He teaches both classical violin and traditional Irish fiddle and has been an active participant in Irish music groups like Cairde na Gael. His expertise has led him to teach at various workshops and festivals, where he shares his passion for Irish music with others.`,
            `Whether performing solo or as part of a group, Eric Ryan-Johnson brings a rich blend of musical traditions to his work, making him a dynamic and influential figure in the Tulsa music scene.`
        ],
        spotifyUrl: "2yh8yQClY7aQ4evzoAHzZ7?utm_source=generator&theme=0",
        fbLink: "https://www.facebook.com/ericryanjohnsonband",
        igLink: "https://www.instagram.com/e.ryanjohnson/",
        ttLink: "https://www.tiktok.com/@e.ryanjohnson",
        ytLink: "https://www.youtube.com/channel/UC2glDyvuSE9Iyz6DwSRlWfA",
        bcLink: "https://ericryanjohnson.bandcamp.com",
    },
    {
        name: "Jeff Bush",
        pics: ["jeff-bush-1","jeff-bush-2", "jeff-bush-3", "jeff-bush-4", "jeff-bush-5"],
        urlName: "jeff-bush",
        ogPic: "jeff-bush-og",
        bioText: [
            `is a folk punk ukulele player whose sound is as raw and emotional as it is versatile. Influenced by artists like Amigo the Devil and Weird Al, as well as classic rock, old country, and folk punk, he brings a unique blend of intensity and heartfelt storytelling to his music.`,
            `After casually playing guitar in high school and college, Jeff stepped away from music for years. In 2023, he rediscovered his passion, this time through the ukulele, which reignited his love for creating music. Since then, he has been honing his craft, performing at various venues around Tulsa including Lot No. 6 and Soundpony, as well as busking in downtown Tulsa where he  captivates passersbys with his dynamic vocal range that shifts from clean tones to raspy growls and powerful screams.`,
            `Jeff's music is deeply personal, reflecting his own experiences and emotions, and he pours this raw energy into every performance. His songs resonate with authenticity, drawing listeners into the stories he tells through his lyrics and melodies.`,
            `Currently, Jeff is dedicated to improving his skills and working towards releasing his first album by the end of the year. His journey in music is just beginning, but his passion and commitment already make him a compelling force in the folk punk scene, leaving a lasting impact on everyone who hears him play.`
        ],
        spotifyUrl: "7jV8Cj5bqsja5xOXainG8i?utm_source=generator&theme=0",
        fbLink: "https://www.facebook.com/profile.php?id=695022605",
        igLink: "",
        ttLink: "https://www.tiktok.com/@jefftrieshisbest",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "Chris Ray",
        pics: ["chris-ray-1","chris-ray-2", "chris-ray-3", "chris-ray-4", "chris-ray-5"],
        ogPic: "chris-ray-og",
        urlName: "chris-ray",
        bioText: [
            `blends 90s grunge with a modern edge, influenced by Alice in Chains, Soundgarden, and Ray LaMontagne. His sound pulls from an eclectic mix of genres, including blues, punk, and pop, reflecting a lifetime of musical exploration.`,
            `Chris started performing at a young age, inspired by family jam sessions and campfire singalongs. His career began at coffee shops and riverside gigs, leading to performances at venues like The Bowery and Harvard Sports Bar, where his music left lasting impressions.`,
            `Known for reading the room and creating memorable experiences, Chris has performed at events like Inola Hay Days and American Airlines employee parties. He is proud of his ability to engage audiences across genres, whether through original songs or personalized setlists.`,
            `Chris's goal is to complete and release a collection of 10 songs, blending new ideas with past inspirations. With five tracks nearly finished, he is determined to keep writing, refining, and sharing his music with the world.`
        ],
        spotifyUrl: "",
        fbLink: "https://www.facebook.com/profile.php?id=100093616841458",
        igLink: "https://www.instagram.com/christopherray862/",
        ttLink: "https://www.tiktok.com/@misterchrisr?lang=en",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "Josh Thorne",
        pics: ["josh-thorne-1","josh-thorne-2", "josh-thorne-3", "josh-thorne-4", "josh-thorne-5"],
        ogPic: "josh-thorne-og",
        urlName: "josh-thorne",
        bioText: [
            `delivers a unique blend of psychedelic pop, drawing influence from the Beatles, Grandaddy, Radiohead, and Animal Collective. With folk roots and a knack for Phish-style jamming, he creates warm, captivating recordings that reflect both depth and playfulness.`,
            `Known for his good stage presence and engaging with patrons, Josh offers performances that leave a lasting impression. His songwriting and playing stand out, bringing originality to every venue, from cafes to bars.`,
            `Josh's music merges Wilco-inspired writing with the dynamic sounds of Chicago and Boston, creating an eclectic mix that resonates with diverse audiences.`,
            `Currently, he aims to continue writing and recording while pursuing opportunities to open for bands and perform at intimate venues, spreading his evolving sound far and wide.`
        ],
        spotifyUrl: "",
        fbLink: "https://www.facebook.com/people/Josh-Thorne/pfbid0qd34YN82gmsfbZT6fipfUhicAZ2jtg1RYQtypPqbwXxLZCFtoS3obsAnbHZzYGnvl/",
        igLink: "",
        ttLink: "",
        ytLink: "https://www.youtube.com/channel/UCZTcgIxQKuY2i7oNgDBDfXA",
        bcLink: "",
    },
    {
        name: "Vic Ortega",
        pics: ["vic-ortega-1", "vic-ortega-2", "vic-ortega-3", "vic-ortega-4", "vic-ortega-5"],
        ogPic: "vic-ortega-og",
        urlName: "vic-ortega",
        bioText: [
            `delivers a mix of alternative, grunge, and folk sounds, drawing inspiration from artists like Mazzy Star, Adele, Chris Cornell, and Eddie Vedder. Their music reflects a blend of introspective melodies and raw emotion, offering a unique take on familiar genres.`,
            `Vic has performed at a variety of venues, including Tap on the Tracks, Sidecar, Gypsy Coffee House, McKinney’s, Toast, and Tulsa Zoo. Their performances create a joyous and uplifting atmosphere, often captivating audiences and encouraging heartfelt applause.`,
            `Growing up with a deep connection to music, Vic's parents nurtured their passion by enrolling them in music programs. Moving to Tulsa was a pivotal moment, introducing them to a diverse music community where they felt right at home.`,
            `Vic’s current goal is to make music a full-time pursuit, using their art to inspire others. With multiple singles and albums ready to be recorded, they aim to turn their latest songwriting efforts into reality, reinvesting their earnings back into their craft.`
        ],
        spotifyUrl: "2gmYgjnkhGHkx651qI4GiD?utm_source=generator",
        fbLink: "https://www.facebook.com/vicortegamusic",
        igLink: "https://www.instagram.com/vicortegamusic/",
        ttLink: "https://www.tiktok.com/@vicortegamusic",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "FrayTus",
        pics: ["fraytus-1", "fraytus-2", "fraytus-3", "fraytus-4", "fraytus-5"],
        ogPic: "fraytus-og",
        urlName: "fraytus",
        bioText: [
            `blends grunge, rap-rock, and hip-hop into a high-energy, hard-hitting sound influenced by Korn, Nirvana, Rage Against the Machine, and Wu-Tang Clan. As a live loop artist, he builds his music layer by layer in real time, delivering an electrifying and unpredictable performance every time he steps on stage.`,
            `With experience performing across eight states, FrayTus has played at festivals and venues like the OKC State Fair, Creek County Fair, and Rawk the River Festival. His ability to command a stage and create massive soundscapes on the fly sets him apart from other artists in the scene.`,
            `His journey began at 14 when he saw a kid playing guitar and knew he had to do the same. Years later, after discovering Tash Sultana’s looping techniques, he transformed his sound, incorporating raw, unfiltered energy into every performance.`,
            `Always evolving, FrayTus continues to write, record, and push the boundaries of his music. With new releases on the horizon, he’s constantly innovating, proving that his artistry is just getting started.`
        ],
        spotifyUrl: "6u6fD16y2MxAO3HZf3B1mZ?utm_source=generator&theme=0",
        fbLink: "https://www.facebook.com/FrayTus/",
        igLink: "https://www.instagram.com/fraytus/?hl=en",
        ttLink: "https://www.tiktok.com/@fraytus",
        ytLink: "https://www.youtube.com/channel/UChu86ZFfS3NiSEXufsQA-uw",
        bcLink: "",
    },
    {
        name: "Davaughnte Hill",
        pics: ["davaughnte-hill-1", "davaughnte-hill-2", "davaughnte-hill-3", "davaughnte-hill-4"],
        ogPic: "davaughnte-hill-og",
        urlName: "davaughnte-hill",
        bioText: [
            `brings a universal style to his music, shaped by the soulfulness of rhythm and blues and a foundation built in church choirs. His sound blends heartfelt melodies with an energetic presence that captivates any audience.`,
            `His performances range from bars and alleyway parties to college campuses. A standout moment in his career was playing at Dickinson State University, where he entertained an entire town and felt the thrill of performing on a college stage.`,
            `Starting with church and school choirs, Davaughnte discovered his passion for music in unexpected ways. Those early experiences prepared him for this journey, leading to moments when listeners first celebrated his natural talent.`,
            `With ambitions to be one of the greatest singer-songwriters, Davaughnte is constantly collaborating with Oklahoma artists. He’s gearing up to release a new single, finalize an EP, and work toward his ultimate goal: performing at Tulsa’s iconic BOK Center.`
        ],
        spotifyUrl: "11ZrJczc8P1RNLllDln7S9?utm_source=generator",
        fbLink: "https://www.facebook.com/profile.php?id=100084237335680",
        igLink: "https://www.instagram.com/dhill_music ",
        ttLink: "https://www.tiktok.com/@dhillmusicc",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "Andre Chisum",
        pics: ["andre-chisum-1","andre-chisum-2","andre-chisum-3","andre-chisum-4","andre-chisum-5","andre-chisum-6","andre-chisum-7","andre-chisum-8","andre-chisum-9",],
        ogPic: "andre-chisum-og",
        urlName: "andre-chisum",
        bioText: [
            `combines 90s grunge and 70s country influences, writing heartfelt original songs while performing a wide range of covers. His inspirations, including Nirvana and Merle Haggard, echo in both his music and performances.`,
            `Starting in his family band, The Rusty Tornadoes, Andre quickly made a name for himself. As a solo artist, he’s played venues like The Blue Rose, Grumpy’s Tavern, and The District Bar and Grill. With his band, Okra and the Universe, Andre has performed at Mayfest and The Venue Shrine, among others. He’s also part of Tulsa’s open mic circuit, frequenting spots like Broken Arrow Brewing Co. and Lot No. 6.`,
            `Andre stands out with his loyal following, drawing crowds of friends and family who love his music and support his journey. Whether solo or in collaboration, his performances promise an engaging experience that resonates deeply with audiences.`,
            `Currently, Andre balances three projects: his solo acoustic shows, an acoustic duo Mae ‘N Dre with Mae Bartel, and playing bass with Okra and the Universe. He’s actively writing, recording, and growing as an artist, aiming to leave a lasting mark on the local music scene and beyond.`
        ],
        spotifyUrl: "2HLDLV7SRwYxCp228iwoeK?utm_source=generator",
        fbLink: "https://www.facebook.com/andre.chisum",
        igLink: "https://www.instagram.com/andrechisummusic/",
        ttLink: "https://www.tiktok.com/@andrechisummusic?lang=en",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "Rench In the Works",
        pics: ["rench-1", "rench-2", "rench-3", "rench-4", "rench-5"],
        ogPic: "rench-og",
        urlName: "rench-in-the-works",
        bioText: [
            `grew up with an eclectic musical upbringing, influenced by their parents’ road trips filled with everything from The Beatles and The Beach Boys to Frank Sinatra and Barry Manilow. In their adolescence, they discovered Def Leppard, Metallica, and punk, which shaped their musical philosophy: do what you want, and anything goes.`,
            `Their sound blends early influences like Sinatra and The Beach Boys with punk icons like The Misfits and NOFX, as well as reggae and hip-hop from artists like Bob Marley and A Tribe Called Quest. Rench’s music reflects a wide range of genres, defying strict categorization.`,
            `Throughout their journey, they have embraced the freedom of musical exploration, often mixing unexpected styles. Whether it's folk-inspired storytelling or punk energy, Rench ensures their sound remains distinct and dynamic.`,
            `With roots in both performance and production, Rench continues to evolve, creating music that resonates across genres and generations. Their passion for music lies in crafting something meaningful, no matter the style or setting.`
        ],
        spotifyUrl: "",
        fbLink: "https://www.facebook.com/search/top?q=rench%20in%20the%20works",
        igLink: "https://www.instagram.com/rench.in.the.wrx/",
        ttLink: "",
        ytLink: "",
        bcLink: "",
    },
    {
        name: "Joey Carter",
        pics: ["joey-carter-1", "joey-carter-2", "joey-carter-3", "joey-carter-4", "joey-carter-5", "joey-carter-6", "joey-carter-7", "joey-carter-8"],
        ogPic: "joey-carter-og",
        urlName: "joey-carter",
        bioText: [
            ` is a raw, unfiltered singer-songwriter blending folk, punk, blues, and dark country. Influenced by legends like Townes Van Zandt and Johnny Cash, his music is crafted to make listeners think and feel. Whether acoustic or full-band, his songs capture life’s struggles, triumphs, and hard truths.`,
            `From playing lead guitar in a hardcore band at The Vanguard to performing at Tulsa’s open mic and songwriter nights, Joey has brought music to a variety of stages. However, one of the most powerful performances wasn’t at a traditional venue—it was at a rehabilitation facility in Florida. Playing for a room of strangers who were fighting their own battles, Joey saw firsthand how music could bring people together, offering comfort, laughter, and connection in a way that transcends location or circumstance.`,
            `Every performance is played like it could be the last, carrying an intensity and authenticity that sets Joey apart. His songs are brutally honest, reflecting life’s struggles in a way that resonates deeply with audiences. With a focus on original music that challenges perspectives and evokes strong emotions, Joey’s presence on stage is both intimate and powerful, leaving listeners with something to carry long after the last note fades.`,
            `Music has been part of Joey’s life since childhood, starting with the cowboy chords his grandfather taught him. From being dragged into nursing homes to play for lonely residents to finding his own voice through songwriting, music has always been more than just a passion—it’s a purpose. Now, Joey is working on his debut full-length album and continuing to play anywhere and everywhere, with the simple goal of making people feel something.`
        ],
        spotifyUrl: "",
        fbLink: "https://www.facebook.com/profile.php?id=61567185576958",
        igLink: "https://www.instagram.com/joeycarterandthenoshows/",
        ttLink: "",
        ytLink: "https://www.youtube.com/@JoeyandTheNoShows",
        bcLink: "",
    },
    // {
    //     name: "",
    //     pics: ["first-last-1", "first-last-2", "first-last-3", "first-last-4", "first-last-5"],
    //     ogPic: "first-last-og",
    //     urlName: "first-last",
    //     bioText: [
    //         ``,
    //         ``,
    //         ``,
    //         ``
    //     ],
    //     spotifyUrl: "",
    //     fbLink: "",
    //     igLink: "",
    //     ttLink: "",
    //     ytLink: "",
    //     bcLink: "",
    // },
]}

export default monsterList;