import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lacquer } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/navbar";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });
const lacquer = Lacquer({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lacquer.className}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
